export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOAD_USERS_PENDING = 'LOAD_USERS_PENDING';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';